# Generated by Django 2.2.3 on 2019-07-31 00:41

from django.db import migrations, models
import django.db.models.deletion
import ninagram.cache


class Migration(migrations.Migration):

    dependencies = [
        ('ninagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('intern', models.FileField(upload_to='ninagram')),
                ('type', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ninagram.Message')),
            ],
            bases=(models.Model, ninagram.cache.SimpleCache),
        ),
    ]
